### PR TITLE
fix mersher to mesher

### PR DESCRIPTION
**Pull request by yuyang-gif**
fix mersher to mesher

### CODE REVIEW

**Comment by chanjarster** [comment]
Thanks, considering this PR is big, there need to be a JIRA for it. Follow this [link](http://servicecomb.apache.org/developers/use-jira/) to create a JIRA and then update PR title to `SCB-XXX blah blah`

Besides, there are some minor issues for this PR:

1. the upstream target branch should be **master**, not **asf-site**, you may need to close this PR and create another one.
2. the files named `mersher` should also be renamed to `mesher`

**Comment by zaneChou1** [comment]
I created a JIRA [SCB-1648](https://issues.apache.org/jira/browse/SCB-1648)

**Comment by chanjarster** [comment]
@zaneChou1 Good job, now you should close this PR, create another one and fix other issues I mentioned.

**Comment by zaneChou1** [comment]
> @zaneChou1 Good job, now you should close this PR, create another one and fix other issues I mentioned.

I don't have permission to close this PR, @yuyang-gif should continue to do this.

**Comment by chanjarster** [comment]
Oh, I didn't notice that you are not the same person. LOL.

**Comment by SmartsYoung** [comment]
Another question is need to focus,  some of wrods are "Mesher", not "mesher".

**Comment by WillemJiang** [comment]
OK, I will merge the patch to master branch.

**Pull request merged**
