### PR TITLE
Apache ServiceComb meetup at BUPT

### PR DESCRIPTION
**Pull request by ChinX**

### CODE REVIEW

**Comment by MabinGo** [comment]
LGTM

**Comment by chanjarster** [comment]
Ehh, I think the target branch was wrong, it should be master, not asf-site.

**Comment by ChinX** [comment]
> Ehh, I think the target branch was wrong, it should be master, not asf-site.

Sorry, I submitted the PR to the wrong target branch.
I have resubmitted the PR. 
I hope there is no trouble.

**Comment by chanjarster** [comment]
@ChinX You could click the revert button and revert this merge

**Pull request merged**
